# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c44ae20197fce928d54a76621625694615aaedc7fae3b82bfbb6ac33aa13de53a49d5cf1dde67161a8031355622100ade247dbb6725b98952600df2039c25e5

test:
  secret_key_base: 4600e2f1b03e84afe7f3cbe5a59bc846690d934ac36bb4224f4c75412d2af1783ae76deab6773c7565abdce27cb4decd094e212119d769a818fd500d4e35db54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
